#pragma once

enum class STATE {
    BLOCK,
    BLOCK_V,
    BLOCK_VA,
    BLOCK_VAR,
    BLOCK_C,
    BLOCK_CO,
    BLOCK_CON,
    BLOCK_CONS,
    BLOCK_CONST,
    BLOCK_L,
    BLOCK_LE,
    BLOCK_LET,
    BLOCK_F,
    BLOCK_FU,
    BLOCK_FUN,
    BLOCK_FUNC,
    BLOCK_FUNCT,
    BLOCK_FUNCTI,
    BLOCK_FUNCTIO,
    BLOCK_FUNCTION,
    EXPECT_IDENTIFIER,
    IDENTIFIER_NAME,
    IDENTIFIER_COMPLETE,
    EXPECT_TYPE_ANNOTATION,
    TYPE_ANNOTATION,
    EXPECT_EQUALS,
    EXPRESSION_EXPECT_OPERAND,
    EXPRESSION_AFTER_OPERAND,
    EXPRESSION_AFTER_OPERAND_NEW_LINE,
    EXPRESSION_NUMBER,
    EXPRESSION_IDENTIFIER,
    EXPRESSION_SINGLE_QUOTE,
    EXPRESSION_SINGLE_QUOTE_ESCAPE,
    EXPRESSION_DOUBLE_QUOTE,
    EXPRESSION_DOUBLE_QUOTE_ESCAPE,
    EXPRESSION_PLUS,
    EXPRESSION_MINUS,
    EXPRESSION_LESS,
    EXPRESSION_GREATER,
    EXPRESSION_EQUALS,
    EXPRESSION_EQUALS_DOUBLE,
    EXPRESSION_NOT,
    EXPRESSION_NOT_EQUALS,
    EXPRESSION_AND,
    EXPRESSION_OR,
    EXPECT_IMMEDIATE_IDENTIFIER,
    VARIABLE_CREATE_IDENTIFIER_COMPLETE,
    FUNCTION_PARAMETER_COMPLETE,
    FUNCTION_DECLARATION_NAME,
    FUNCTION_PARAMETERS_START,
    FUNCTION_PARAMETER_NAME,
    FUNCTION_PARAMETER_TYPE_ANNOTATION,
    FUNCTION_PARAMETER_DEFAULT_VALUE,
    FUNCTION_PARAMETER_SEPARATOR,
    FUNCTION_PARAMETERS_END,
    FUNCTION_RETURN_TYPE_ANNOTATION,
    FUNCTION_BODY_START,
    FUNCTION_BODY,
    ARROW_FUNCTION_PARAMETERS,
    ARROW_FUNCTION_ARROW,
    ARROW_FUNCTION_BODY,
    ARRAY_LITERAL_START,
    ARRAY_LITERAL_ELEMENT,
    ARRAY_LITERAL_SEPARATOR,
    OBJECT_LITERAL_START,
    OBJECT_LITERAL_PROPERTY_KEY,
    OBJECT_LITERAL_PROPERTY_COLON,
    OBJECT_LITERAL_PROPERTY_VALUE,
    OBJECT_LITERAL_SEPARATOR,
    // Destructuring states
    ARRAY_DESTRUCTURING_START,
    ARRAY_DESTRUCTURING_ELEMENT,
    ARRAY_DESTRUCTURING_SEPARATOR,
    ARRAY_DESTRUCTURING_REST,
    OBJECT_DESTRUCTURING_START,
    OBJECT_DESTRUCTURING_PROPERTY_KEY,
    OBJECT_DESTRUCTURING_PROPERTY_COLON,
    OBJECT_DESTRUCTURING_PROPERTY_VALUE,
    OBJECT_DESTRUCTURING_SEPARATOR,
    OBJECT_DESTRUCTURING_REST,
    IF_CONDITION_START,
    IF_CONSEQUENT,
    IF_ALTERNATE_START,
    IF_ALTERNATE,
    BLOCK_W,
    BLOCK_WH,
    BLOCK_WHI,
    BLOCK_WHIL,
    BLOCK_WHILE,
    WHILE_CONDITION_START,
    WHILE_BODY,
    // New states for missing TypeScript features
    EXPRESSION_PLUS_PLUS,
    EXPRESSION_MINUS_MINUS,
    EXPRESSION_LOGICAL_NOT,
    EXPRESSION_UNARY_PLUS,
    EXPRESSION_UNARY_MINUS,
    EXPRESSION_BITWISE_NOT,
    EXPRESSION_EXPONENT,
    EXPRESSION_BIT_AND,
    EXPRESSION_BIT_OR,
    EXPRESSION_BIT_XOR,
    EXPRESSION_LEFT_SHIFT,
    EXPRESSION_RIGHT_SHIFT,
    EXPRESSION_UNSIGNED_RIGHT_SHIFT,
    EXPRESSION_ADD_ASSIGN,
    EXPRESSION_SUBTRACT_ASSIGN,
    EXPRESSION_MULTIPLY_ASSIGN,
    EXPRESSION_DIVIDE_ASSIGN,
    EXPRESSION_MODULO_ASSIGN,
    EXPRESSION_EXPONENT_ASSIGN,
    EXPRESSION_LEFT_SHIFT_ASSIGN,
    EXPRESSION_RIGHT_SHIFT_ASSIGN,
    EXPRESSION_UNSIGNED_RIGHT_SHIFT_ASSIGN,
    EXPRESSION_BIT_AND_ASSIGN,
    EXPRESSION_BIT_OR_ASSIGN,
    EXPRESSION_BIT_XOR_ASSIGN,
    EXPRESSION_AND_ASSIGN,
    EXPRESSION_OR_ASSIGN,
    EXPRESSION_NULLISH_ASSIGN,
    EXPRESSION_TEMPLATE_LITERAL_START,
    EXPRESSION_TEMPLATE_LITERAL,
    EXPRESSION_TEMPLATE_LITERAL_ESCAPE,
    EXPRESSION_TEMPLATE_LITERAL_INTERPOLATION,
    EXPRESSION_REGEXP_START,
    EXPRESSION_REGEXP,
    EXPRESSION_REGEXP_ESCAPE,
    EXPRESSION_REGEXP_FLAGS,
    BLOCK_D,
    BLOCK_DO,
    BLOCK_DOW,
    BLOCK_DOWH,
    BLOCK_DOWHI,
    BLOCK_DOWHIL,
    BLOCK_DOWHILE,
    DO_BODY_START,
    DO_BODY,
    DO_WHILE_CONDITION_START,
    BLOCK_FO,
    BLOCK_FOR,
    FOR_INIT_START,
    FOR_INIT,
    FOR_TEST_START,
    FOR_TEST,
    FOR_UPDATE_START,
    FOR_UPDATE,
    FOR_BODY_START,
    FOR_BODY,
    BLOCK_S,
    BLOCK_SW,
    BLOCK_SWI,
    BLOCK_SWIT,
    BLOCK_SWITC,
    BLOCK_SWITCH,
    SWITCH_CONDITION_START,
    SWITCH_BODY_START,
    SWITCH_BODY,
    SWITCH_CASE_START,
    SWITCH_CASE,
    SWITCH_DEFAULT_START,
    SWITCH_DEFAULT,
    BLOCK_E,
    BLOCK_EL,
    BLOCK_ELS,
    BLOCK_ELSE,
    BLOCK_T,
    BLOCK_TR,
    BLOCK_TRY,
    TRY_BODY_START,
    TRY_BODY,
    TRY_CATCH_START,
    TRY_CATCH,
    TRY_CATCH_PARAM_START,
    TRY_CATCH_PARAM,
    TRY_CATCH_BODY_START,
    TRY_CATCH_BODY,
    TRY_FINALLY_START,
    TRY_FINALLY,
    TRY_FINALLY_BODY_START,
    TRY_FINALLY_BODY,
    FUNCTION_EXPRESSION_START,
    FUNCTION_EXPRESSION_PARAMETERS_START,
    FUNCTION_EXPRESSION_PARAMETER_NAME,
    FUNCTION_EXPRESSION_PARAMETER_TYPE_ANNOTATION,
    FUNCTION_EXPRESSION_PARAMETER_DEFAULT_VALUE,
    FUNCTION_EXPRESSION_PARAMETER_SEPARATOR,
    FUNCTION_EXPRESSION_PARAMETERS_END,
    FUNCTION_EXPRESSION_RETURN_TYPE_ANNOTATION,
    FUNCTION_EXPRESSION_BODY_START,
    FUNCTION_EXPRESSION_BODY,
    BLOCK_I,
    BLOCK_IN,
    BLOCK_INT,
    BLOCK_INTE,
    BLOCK_INTER,
    BLOCK_INTERF,
    BLOCK_INTERFA,
    BLOCK_INTERFAC,
    BLOCK_INTERFACE,
    INTERFACE_DECLARATION_NAME,
    INTERFACE_AFTER_NAME_START,
    INTERFACE_AFTER_NAME_NAME,
    INTERFACE_AFTER_NAME_SEPARATOR,
    INTERFACE_BODY_START,
    INTERFACE_BODY,
    INTERFACE_PROPERTY_KEY,
    INTERFACE_PROPERTY_TYPE,
    INTERFACE_PROPERTY_TYPE_NAME,
    INTERFACE_PROPERTY_TYPE_END,
    INTERFACE_PROPERTY_OPTIONAL,
    INTERFACE_PROPERTY_READONLY,
    INTERFACE_METHOD_PARAMETERS_START,
    INTERFACE_METHOD_PARAMETERS_END,
    INTERFACE_METHOD_RETURN_TYPE,
    INTERFACE_INDEX_SIGNATURE_START,
    INTERFACE_INDEX_SIGNATURE_KEY,
    INTERFACE_INDEX_SIGNATURE_KEY_NAME,
    INTERFACE_INDEX_SIGNATURE_KEY_TYPE,
    INTERFACE_INDEX_SIGNATURE_KEY_TYPE_NAME,
    INTERFACE_INDEX_SIGNATURE_KEY_TYPE_END,
    INTERFACE_INDEX_SIGNATURE_VALUE_TYPE,
    INTERFACE_INDEX_SIGNATURE_VALUE_TYPE_NAME,
    INTERFACE_INDEX_SIGNATURE_VALUE_TYPE_END,
    INTERFACE_INDEX_SIGNATURE_READONLY,
    INTERFACE_CALL_SIGNATURE_START,
    INTERFACE_CALL_SIGNATURE_PARAMETERS_START,
    INTERFACE_CALL_SIGNATURE_PARAMETERS_END,
    INTERFACE_CALL_SIGNATURE_RETURN_TYPE,
    INTERFACE_CONSTRUCT_SIGNATURE_START,
    INTERFACE_CONSTRUCT_SIGNATURE_PARAMETERS_START,
    INTERFACE_CONSTRUCT_SIGNATURE_PARAMETERS_END,
    INTERFACE_CONSTRUCT_SIGNATURE_RETURN_TYPE,
    BLOCK_CL,
    BLOCK_CLA,
    BLOCK_CLAS,
    BLOCK_CLASS,
    CLASS_DECLARATION_NAME,
    CLASS_AFTER_NAME_START,
    CLASS_AFTER_NAME_NAME,
    CLASS_IMPLEMENTS_START,
    CLASS_IMPLEMENTS_NAME,
    CLASS_IMPLEMENTS_SEPARATOR,
    CLASS_BODY_START,
    CLASS_BODY,
    CLASS_STATIC_START,
    CLASS_PROPERTY_KEY,
    CLASS_PROPERTY_TYPE,
    CLASS_PROPERTY_INITIALIZER,
    CLASS_METHOD_PARAMETERS_START,
    CLASS_METHOD_PARAMETERS_END,
    CLASS_METHOD_RETURN_TYPE,
    CLASS_METHOD_BODY_START,
    CLASS_METHOD_BODY,
    // New class feature states
    CLASS_ACCESS_MODIFIER_PUBLIC,
    CLASS_ACCESS_MODIFIER_PRIVATE,
    CLASS_ACCESS_MODIFIER_PROTECTED,
    CLASS_READONLY_MODIFIER,
    CLASS_ABSTRACT_MODIFIER,
    CLASS_GETTER_START,
    CLASS_SETTER_START,
    CLASS_GETTER_NAME,
    CLASS_SETTER_NAME,
    CLASS_GETTER_PARAMETERS_START,
    CLASS_SETTER_PARAMETERS_START,
    CLASS_GETTER_BODY_START,
    CLASS_SETTER_BODY_START,
    CLASS_GETTER_BODY,
    CLASS_SETTER_BODY,
    // Generic type states
    TYPE_GENERIC_PARAMETERS_START,
    TYPE_GENERIC_PARAMETER_NAME,
    TYPE_GENERIC_PARAMETER_SEPARATOR,
    TYPE_GENERIC_PARAMETERS_END,
    TYPE_GENERIC_TYPE_START,
    TYPE_GENERIC_TYPE_ARGUMENTS,
    // Interface generic states
    INTERFACE_GENERIC_PARAMETERS_START,
    INTERFACE_GENERIC_PARAMETER_NAME,
    INTERFACE_GENERIC_PARAMETER_SEPARATOR,
    INTERFACE_GENERIC_PARAMETERS_END,
    // Class generic states
    CLASS_GENERIC_PARAMETERS_START,
    CLASS_GENERIC_PARAMETER_NAME,
    CLASS_GENERIC_PARAMETER_SEPARATOR,
    CLASS_GENERIC_PARAMETERS_END,
    // Function generic states
    FUNCTION_GENERIC_PARAMETERS_START,
    FUNCTION_GENERIC_PARAMETER_NAME,
    FUNCTION_GENERIC_PARAMETER_SEPARATOR,
    FUNCTION_GENERIC_PARAMETERS_END,
    // Module import/export states
    BLOCK_IM,
    BLOCK_IMP,
    BLOCK_IMPO,
    BLOCK_IMPOR,
    BLOCK_IMPORT,
    IMPORT_SPECIFIERS_START,
    IMPORT_SPECIFIER_NAME,
    IMPORT_SPECIFIER_LOCAL_NAME,
    IMPORT_SPECIFIER_SEPARATOR,
    IMPORT_SPECIFIERS_END,
    IMPORT_FROM,
    IMPORT_SOURCE_START,
    IMPORT_SOURCE,
    IMPORT_SOURCE_END,
    BLOCK_EX,
    BLOCK_EXP,
    BLOCK_EXPO,
    BLOCK_EXPOR,
    BLOCK_EXPORT,
    EXPORT_SPECIFIERS_START,
    EXPORT_SPECIFIER_NAME,
    EXPORT_SPECIFIER_AS,
    EXPORT_SPECIFIER_EXPORTED_NAME,
    EXPORT_SPECIFIER_SEPARATOR,
    EXPORT_SPECIFIERS_END,
    EXPORT_FROM,
    EXPORT_SOURCE_START,
    EXPORT_SOURCE,
    EXPORT_SOURCE_END,
    EXPORT_DEFAULT,
    EXPORT_ALL,
    EXPORT_DECLARATION,
    // Async/await states
    BLOCK_A,
    BLOCK_AS,
    BLOCK_ASY,
    BLOCK_ASYN,
    BLOCK_ASYNC,
    BLOCK_AW,
    BLOCK_AWA,
    BLOCK_AWAI,
    BLOCK_AWAIT,
    EXPRESSION_AWAIT,
    // Enum states
    BLOCK_ENUM_E,
    BLOCK_ENUM_EN,
    BLOCK_ENUM_ENU,
    ENUM_DECLARATION_NAME,
    ENUM_BODY_START,
    ENUM_BODY,
    ENUM_MEMBER_NAME,
    ENUM_MEMBER_INITIALIZER,
    ENUM_MEMBER_SEPARATOR,
    // Type alias states
    BLOCK_TY,
    BLOCK_TYP,
    BLOCK_TYPE,
    TYPE_ALIAS_NAME,
    TYPE_ALIAS_GENERIC_PARAMETERS_START,
    TYPE_ALIAS_GENERIC_PARAMETER_NAME,
    TYPE_ALIAS_GENERIC_PARAMETER_SEPARATOR,
    TYPE_ALIAS_GENERIC_PARAMETERS_END,
    TYPE_ALIAS_EQUALS,
    TYPE_ALIAS_TYPE,
    // Advanced generics states
    TYPE_CONDITIONAL_CHECK,
    TYPE_CONDITIONAL_E,
    TYPE_CONDITIONAL_EX,
    TYPE_CONDITIONAL_EXT,
    TYPE_CONDITIONAL_EXTE,
    TYPE_CONDITIONAL_EXTEN,
    TYPE_CONDITIONAL_EXTEND,
    TYPE_CONDITIONAL_EXTENDS,
    TYPE_CONDITIONAL_TRUE,
    TYPE_CONDITIONAL_FALSE,
    TYPE_CONDITIONAL_QUESTION,
    TYPE_INFER_I,
    TYPE_INFER_IN,
    TYPE_INFER_INF,
    TYPE_INFER_INFE,
    TYPE_INFER_INFER,
    TYPE_INFER_START,
    TYPE_INFER_NAME,
    TYPE_TEMPLATE_LITERAL_START,
    TYPE_TEMPLATE_LITERAL_QUASI,
    TYPE_TEMPLATE_LITERAL_INTERPOLATION,
    TYPE_MAPPED_START,
    TYPE_MAPPED_R,
    TYPE_MAPPED_RE,
    TYPE_MAPPED_REA,
    TYPE_MAPPED_READ,
    TYPE_MAPPED_READO,
    TYPE_MAPPED_READON,
    TYPE_MAPPED_READONL,
    TYPE_MAPPED_READONLY,
    TYPE_MAPPED_PARAMETER,
    TYPE_MAPPED_I,
    TYPE_MAPPED_IN,
    TYPE_MAPPED_IN_CONSTRAINT,
    TYPE_MAPPED_CONSTRAINT,
    TYPE_MAPPED_A,
    TYPE_MAPPED_AS,
    TYPE_MAPPED_AS_NAME,
    TYPE_MAPPED_VALUE,
    TYPE_MAPPED_OPTIONAL,
    // Interface after name states
    INTERFACE_AFTER_NAME_E,
    INTERFACE_AFTER_NAME_EX,
    INTERFACE_AFTER_NAME_EXT,
    INTERFACE_AFTER_NAME_EXTE,
    INTERFACE_AFTER_NAME_EXTEN,
    INTERFACE_AFTER_NAME_EXTEND,
    INTERFACE_AFTER_NAME_EXTENDS,
    // Interface member modifier states
    INTERFACE_MEMBER_R,
    INTERFACE_MEMBER_RE,
    INTERFACE_MEMBER_REA,
    INTERFACE_MEMBER_READ,
    INTERFACE_MEMBER_READO,
    INTERFACE_MEMBER_READON,
    INTERFACE_MEMBER_READONL,
    INTERFACE_MEMBER_READONLY,
    // Interface member "new" keyword states
    INTERFACE_MEMBER_N,
    INTERFACE_MEMBER_NE,
    INTERFACE_MEMBER_NEW,
    // Class after name states
    CLASS_AFTER_NAME_E,
    CLASS_AFTER_NAME_EX,
    CLASS_AFTER_NAME_EXT,
    CLASS_AFTER_NAME_EXTE,
    CLASS_AFTER_NAME_EXTEN,
    CLASS_AFTER_NAME_EXTEND,
    CLASS_AFTER_NAME_EXTENDS,
    // Class inheritance identifier states
    CLASS_INHERITANCE_I,
    CLASS_INHERITANCE_IM,
    CLASS_INHERITANCE_IMP,
    CLASS_INHERITANCE_IMPL,
    CLASS_INHERITANCE_IMPLE,
    CLASS_INHERITANCE_IMPLEM,
    CLASS_INHERITANCE_IMPLEME,
    CLASS_INHERITANCE_IMPLEMEN,
    CLASS_INHERITANCE_IMPLEMENTS,
    // Module import/export keyword states
    POST_IMPORT_SPECIFIER_A,
    IMPORT_SPECIFIER_AFTER_AS,
    IMPORT_SPECIFIER_AS,
    IMPORT_FROM_F,
    IMPORT_FROM_FR,
    IMPORT_FROM_FRO,
    IMPORT_FROM_FROM,
    EXPORT_A,
    EXPORT_AS,
    EXPORT_AS_A,
    EXPORT_SPECIFIER_AFTER_AS,
    EXPORT_FROM_F,
    EXPORT_FROM_FR,
    EXPORT_FROM_FRO,
    EXPORT_FROM_FROM,
    EXPORT_DEFAULT_D,
    EXPORT_DEFAULT_DE,
    EXPORT_DEFAULT_DEF,
    EXPORT_DEFAULT_DEFA,
    EXPORT_DEFAULT_DEFAU,
    EXPORT_DEFAULT_DEFAUL,
    EXPORT_DEFAULT_DEFAULT,

    EXPORT_V,
    EXPORT_VA,
    EXPORT_VAR,
    EXPORT_F,
    EXPORT_FU,
    EXPORT_FUN,
    EXPORT_FUNC,
    EXPORT_FUNCT,
    EXPORT_FUNCTI,
    EXPORT_FUNCTIO,
    EXPORT_FUNCTION,
    EXPORT_IDENTIFIER,

    // TechnoScript specific features
    BLOCK_P,
    BLOCK_PR,
    BLOCK_PRI,
    BLOCK_PRIN,
    BLOCK_PRINT,
    BLOCK_G,
    BLOCK_GO,
    BLOCK_SE,
    BLOCK_SET,
    BLOCK_SETT,
    BLOCK_SETTI,
    BLOCK_SETTIM,
    BLOCK_SETTIMEO,
    BLOCK_SETTIMEOU,
    BLOCK_SETTIMEOUT,
    BLOCK_SL,
    BLOCK_SLE,
    BLOCK_SLEE,
    BLOCK_SLEEP,
    BLOCK_R,
    BLOCK_RA,
    BLOCK_RAW,
    BLOCK_RAWM,
    BLOCK_RAWME,
    BLOCK_RAWMEM,
    BLOCK_RAWMEMO,
    BLOCK_RAWMEMOR,
    BLOCK_RAWMEMORY,
    BLOCK_TH,
    BLOCK_THI,
    BLOCK_THIS,
    BLOCK_N,
    BLOCK_NE,
    BLOCK_NEW,
    EXPRESSION_MEMBER_ACCESS,
    EXPRESSION_METHOD_CALL,
    EXPRESSION_BRACKET_ACCESS,
    EXPRESSION_NEW,
    EXPRESSION_THIS,
    EXPRESSION_INCREMENT,
    STATEMENT_PRINT,
    STATEMENT_GO,
    STATEMENT_SETTIMEOUT,
    STATEMENT_SLEEP
};

inline const char* stateToString(STATE state) {
    switch (state) {
        case STATE::BLOCK: return "BLOCK";
        case STATE::BLOCK_V: return "V";
        case STATE::BLOCK_VA: return "VA";
        case STATE::BLOCK_VAR: return "VAR";
        case STATE::BLOCK_C: return "C";
        case STATE::BLOCK_CO: return "CO";
        case STATE::BLOCK_CON: return "CON";
        case STATE::BLOCK_CONS: return "CONS";
        case STATE::BLOCK_CONST: return "CONST";
        case STATE::BLOCK_L: return "L";
        case STATE::BLOCK_LE: return "LE";
        case STATE::BLOCK_LET: return "LET";
        case STATE::EXPECT_IDENTIFIER: return "AWAIT_IDENTIFIER";
        case STATE::IDENTIFIER_NAME: return "IDENTIFIER_NAME";
        case STATE::IDENTIFIER_COMPLETE: return "IDENTIFIER_COMPLETE";
        case STATE::EXPECT_TYPE_ANNOTATION: return "AWAIT_TYPE_ANNOTATION";
        case STATE::TYPE_ANNOTATION: return "TYPE_ANNOTATION";
        case STATE::EXPECT_EQUALS: return "AWAIT_EQUALS";
        case STATE::EXPRESSION_EXPECT_OPERAND: return "EXPRESSION_EXPECT_OPERAND";
        case STATE::EXPRESSION_AFTER_OPERAND: return "EXPRESSION_AFTER_OPERAND";
        case STATE::EXPRESSION_AFTER_OPERAND_NEW_LINE: return "EXPRESSION_AFTER_OPERAND_NEW_LINE";
        case STATE::EXPRESSION_NUMBER: return "EXPRESSION_NUMBER";
        case STATE::EXPRESSION_IDENTIFIER: return "EXPRESSION_IDENTIFIER";
        case STATE::EXPRESSION_SINGLE_QUOTE: return "EXPRESSION_SINGLE_QUOTE";
        case STATE::EXPRESSION_SINGLE_QUOTE_ESCAPE: return "EXPRESSION_SINGLE_QUOTE_ESCAPE";
        case STATE::EXPRESSION_DOUBLE_QUOTE: return "EXPRESSION_DOUBLE_QUOTE";
        case STATE::EXPRESSION_DOUBLE_QUOTE_ESCAPE: return "EXPRESSION_DOUBLE_QUOTE_ESCAPE";
        case STATE::EXPRESSION_PLUS: return "EXPRESSION_PLUS";
        case STATE::EXPRESSION_MINUS: return "EXPRESSION_MINUS";
        case STATE::EXPRESSION_LESS: return "EXPRESSION_LESS";
        case STATE::EXPRESSION_GREATER: return "EXPRESSION_GREATER";
        case STATE::EXPRESSION_EQUALS: return "EXPRESSION_EQUALS";
        case STATE::EXPRESSION_EQUALS_DOUBLE: return "EXPRESSION_EQUALS_DOUBLE";
        case STATE::EXPRESSION_NOT: return "EXPRESSION_NOT";
        case STATE::EXPRESSION_NOT_EQUALS: return "EXPRESSION_NOT_EQUALS";
        case STATE::EXPRESSION_AND: return "EXPRESSION_AND";
        case STATE::EXPRESSION_OR: return "EXPRESSION_OR";
        case STATE::EXPECT_IMMEDIATE_IDENTIFIER: return "EXPECT_IMMEDIATE_IDENTIFIER";
        case STATE::VARIABLE_CREATE_IDENTIFIER_COMPLETE: return "VARIABLE_CREATE_IDENTIFIER_COMPLETE";
        case STATE::FUNCTION_PARAMETER_COMPLETE: return "FUNCTION_PARAMETER_COMPLETE";
        case STATE::BLOCK_F: return "F";
        case STATE::BLOCK_FU: return "FU";
        case STATE::BLOCK_FUN: return "FUN";
        case STATE::BLOCK_FUNC: return "FUNC";
        case STATE::BLOCK_FUNCT: return "FUNCT";
        case STATE::BLOCK_FUNCTI: return "FUNCTI";
        case STATE::BLOCK_FUNCTIO: return "FUNCTIO";
        case STATE::BLOCK_FUNCTION: return "FUNCTION";
        case STATE::FUNCTION_DECLARATION_NAME: return "FUNCTION_DECLARATION_NAME";
        case STATE::FUNCTION_PARAMETERS_START: return "FUNCTION_PARAMETERS_START";
        case STATE::FUNCTION_PARAMETER_NAME: return "FUNCTION_PARAMETER_NAME";
        case STATE::FUNCTION_PARAMETER_TYPE_ANNOTATION: return "FUNCTION_PARAMETER_TYPE_ANNOTATION";
        case STATE::FUNCTION_PARAMETER_DEFAULT_VALUE: return "FUNCTION_PARAMETER_DEFAULT_VALUE";
        case STATE::FUNCTION_PARAMETER_SEPARATOR: return "FUNCTION_PARAMETER_SEPARATOR";
        case STATE::FUNCTION_PARAMETERS_END: return "FUNCTION_PARAMETERS_END";
        case STATE::FUNCTION_RETURN_TYPE_ANNOTATION: return "FUNCTION_RETURN_TYPE_ANNOTATION";
        case STATE::FUNCTION_BODY_START: return "FUNCTION_BODY_START";
        case STATE::FUNCTION_BODY: return "FUNCTION_BODY";
        case STATE::ARROW_FUNCTION_PARAMETERS: return "ARROW_FUNCTION_PARAMETERS";
        case STATE::ARROW_FUNCTION_ARROW: return "ARROW_FUNCTION_ARROW";
        case STATE::ARROW_FUNCTION_BODY: return "ARROW_FUNCTION_BODY";
        case STATE::ARRAY_LITERAL_START: return "ARRAY_LITERAL_START";
        case STATE::ARRAY_LITERAL_ELEMENT: return "ARRAY_LITERAL_ELEMENT";
        case STATE::ARRAY_LITERAL_SEPARATOR: return "ARRAY_LITERAL_SEPARATOR";
        case STATE::OBJECT_LITERAL_START: return "OBJECT_LITERAL_START";
        case STATE::OBJECT_LITERAL_PROPERTY_KEY: return "OBJECT_LITERAL_PROPERTY_KEY";
        case STATE::OBJECT_LITERAL_PROPERTY_COLON: return "OBJECT_LITERAL_PROPERTY_COLON";
        case STATE::OBJECT_LITERAL_PROPERTY_VALUE: return "OBJECT_LITERAL_PROPERTY_VALUE";
        case STATE::OBJECT_LITERAL_SEPARATOR: return "OBJECT_LITERAL_SEPARATOR";
        case STATE::ARRAY_DESTRUCTURING_START: return "ARRAY_DESTRUCTURING_START";
        case STATE::ARRAY_DESTRUCTURING_ELEMENT: return "ARRAY_DESTRUCTURING_ELEMENT";
        case STATE::ARRAY_DESTRUCTURING_SEPARATOR: return "ARRAY_DESTRUCTURING_SEPARATOR";
        case STATE::ARRAY_DESTRUCTURING_REST: return "ARRAY_DESTRUCTURING_REST";
        case STATE::OBJECT_DESTRUCTURING_START: return "OBJECT_DESTRUCTURING_START";
        case STATE::OBJECT_DESTRUCTURING_PROPERTY_KEY: return "OBJECT_DESTRUCTURING_PROPERTY_KEY";
        case STATE::OBJECT_DESTRUCTURING_PROPERTY_COLON: return "OBJECT_DESTRUCTURING_PROPERTY_COLON";
        case STATE::OBJECT_DESTRUCTURING_PROPERTY_VALUE: return "OBJECT_DESTRUCTURING_PROPERTY_VALUE";
        case STATE::OBJECT_DESTRUCTURING_SEPARATOR: return "OBJECT_DESTRUCTURING_SEPARATOR";
        case STATE::OBJECT_DESTRUCTURING_REST: return "OBJECT_DESTRUCTURING_REST";
        case STATE::IF_CONDITION_START: return "IF_CONDITION_START";
        case STATE::IF_CONSEQUENT: return "IF_CONSEQUENT";
        case STATE::IF_ALTERNATE_START: return "IF_ALTERNATE_START";
        case STATE::IF_ALTERNATE: return "IF_ALTERNATE";
        case STATE::BLOCK_W: return "W";
        case STATE::BLOCK_WH: return "WH";
        case STATE::BLOCK_WHI: return "WHI";
        case STATE::BLOCK_WHIL: return "WHIL";
        case STATE::BLOCK_WHILE: return "WHILE";
        case STATE::WHILE_CONDITION_START: return "WHILE_CONDITION_START";
        case STATE::WHILE_BODY: return "WHILE_BODY";
        // New states for missing TypeScript features
        case STATE::EXPRESSION_PLUS_PLUS: return "EXPRESSION_PLUS_PLUS";
        case STATE::EXPRESSION_MINUS_MINUS: return "EXPRESSION_MINUS_MINUS";
        case STATE::EXPRESSION_LOGICAL_NOT: return "EXPRESSION_LOGICAL_NOT";
        case STATE::EXPRESSION_UNARY_PLUS: return "EXPRESSION_UNARY_PLUS";
        case STATE::EXPRESSION_UNARY_MINUS: return "EXPRESSION_UNARY_MINUS";
        case STATE::EXPRESSION_BITWISE_NOT: return "EXPRESSION_BITWISE_NOT";
        case STATE::EXPRESSION_EXPONENT: return "EXPRESSION_EXPONENT";
        case STATE::EXPRESSION_BIT_AND: return "EXPRESSION_BIT_AND";
        case STATE::EXPRESSION_BIT_OR: return "EXPRESSION_BIT_OR";
        case STATE::EXPRESSION_BIT_XOR: return "EXPRESSION_BIT_XOR";
        case STATE::EXPRESSION_LEFT_SHIFT: return "EXPRESSION_LEFT_SHIFT";
        case STATE::EXPRESSION_RIGHT_SHIFT: return "EXPRESSION_RIGHT_SHIFT";
        case STATE::EXPRESSION_UNSIGNED_RIGHT_SHIFT: return "EXPRESSION_UNSIGNED_RIGHT_SHIFT";
        case STATE::EXPRESSION_ADD_ASSIGN: return "EXPRESSION_ADD_ASSIGN";
        case STATE::EXPRESSION_SUBTRACT_ASSIGN: return "EXPRESSION_SUBTRACT_ASSIGN";
        case STATE::EXPRESSION_MULTIPLY_ASSIGN: return "EXPRESSION_MULTIPLY_ASSIGN";
        case STATE::EXPRESSION_DIVIDE_ASSIGN: return "EXPRESSION_DIVIDE_ASSIGN";
        case STATE::EXPRESSION_MODULO_ASSIGN: return "EXPRESSION_MODULO_ASSIGN";
        case STATE::EXPRESSION_EXPONENT_ASSIGN: return "EXPRESSION_EXPONENT_ASSIGN";
        case STATE::EXPRESSION_LEFT_SHIFT_ASSIGN: return "EXPRESSION_LEFT_SHIFT_ASSIGN";
        case STATE::EXPRESSION_RIGHT_SHIFT_ASSIGN: return "EXPRESSION_RIGHT_SHIFT_ASSIGN";
        case STATE::EXPRESSION_UNSIGNED_RIGHT_SHIFT_ASSIGN: return "EXPRESSION_UNSIGNED_RIGHT_SHIFT_ASSIGN";
        case STATE::EXPRESSION_BIT_AND_ASSIGN: return "EXPRESSION_BIT_AND_ASSIGN";
        case STATE::EXPRESSION_BIT_OR_ASSIGN: return "EXPRESSION_BIT_OR_ASSIGN";
        case STATE::EXPRESSION_BIT_XOR_ASSIGN: return "EXPRESSION_BIT_XOR_ASSIGN";
        case STATE::EXPRESSION_AND_ASSIGN: return "EXPRESSION_AND_ASSIGN";
        case STATE::EXPRESSION_OR_ASSIGN: return "EXPRESSION_OR_ASSIGN";
        case STATE::EXPRESSION_NULLISH_ASSIGN: return "EXPRESSION_NULLISH_ASSIGN";
        case STATE::EXPRESSION_TEMPLATE_LITERAL_START: return "EXPRESSION_TEMPLATE_LITERAL_START";
        case STATE::EXPRESSION_TEMPLATE_LITERAL: return "EXPRESSION_TEMPLATE_LITERAL";
        case STATE::EXPRESSION_TEMPLATE_LITERAL_ESCAPE: return "EXPRESSION_TEMPLATE_LITERAL_ESCAPE";
        case STATE::EXPRESSION_TEMPLATE_LITERAL_INTERPOLATION: return "EXPRESSION_TEMPLATE_LITERAL_INTERPOLATION";
        case STATE::EXPRESSION_REGEXP_START: return "EXPRESSION_REGEXP_START";
        case STATE::EXPRESSION_REGEXP: return "EXPRESSION_REGEXP";
        case STATE::EXPRESSION_REGEXP_ESCAPE: return "EXPRESSION_REGEXP_ESCAPE";
        case STATE::EXPRESSION_REGEXP_FLAGS: return "EXPRESSION_REGEXP_FLAGS";
        case STATE::BLOCK_D: return "D";
        case STATE::BLOCK_DO: return "DO";
        case STATE::BLOCK_DOW: return "DOW";
        case STATE::BLOCK_DOWH: return "DOWH";
        case STATE::BLOCK_DOWHI: return "DOWHI";
        case STATE::BLOCK_DOWHIL: return "DOWHIL";
        case STATE::BLOCK_DOWHILE: return "DOWHILE";
        case STATE::DO_BODY_START: return "DO_BODY_START";
        case STATE::DO_BODY: return "DO_BODY";
        case STATE::DO_WHILE_CONDITION_START: return "DO_WHILE_CONDITION_START";
        case STATE::BLOCK_FO: return "FO";
        case STATE::BLOCK_FOR: return "FOR";
        case STATE::FOR_INIT_START: return "FOR_INIT_START";
        case STATE::FOR_INIT: return "FOR_INIT";
        case STATE::FOR_TEST_START: return "FOR_TEST_START";
        case STATE::FOR_TEST: return "FOR_TEST";
        case STATE::FOR_UPDATE_START: return "FOR_UPDATE_START";
        case STATE::FOR_UPDATE: return "FOR_UPDATE";
        case STATE::FOR_BODY_START: return "FOR_BODY_START";
        case STATE::FOR_BODY: return "FOR_BODY";
        case STATE::BLOCK_S: return "S";
        case STATE::BLOCK_SW: return "SW";
        case STATE::BLOCK_SWI: return "SWI";
        case STATE::BLOCK_SWIT: return "SWIT";
        case STATE::BLOCK_SWITC: return "SWITC";
        case STATE::BLOCK_SWITCH: return "SWITCH";
        case STATE::SWITCH_CONDITION_START: return "SWITCH_CONDITION_START";
        case STATE::SWITCH_BODY_START: return "SWITCH_BODY_START";
        case STATE::SWITCH_BODY: return "SWITCH_BODY";
        case STATE::SWITCH_CASE_START: return "SWITCH_CASE_START";
        case STATE::SWITCH_CASE: return "SWITCH_CASE";
        case STATE::SWITCH_DEFAULT_START: return "SWITCH_DEFAULT_START";
        case STATE::SWITCH_DEFAULT: return "SWITCH_DEFAULT";
        case STATE::BLOCK_E: return "E";
        case STATE::BLOCK_EL: return "EL";
        case STATE::BLOCK_ELS: return "ELS";
        case STATE::BLOCK_ELSE: return "ELSE";
        case STATE::BLOCK_T: return "T";
        case STATE::BLOCK_TR: return "TR";
        case STATE::BLOCK_TRY: return "TRY";
        case STATE::TRY_BODY_START: return "TRY_BODY_START";
        case STATE::TRY_BODY: return "TRY_BODY";
        case STATE::TRY_CATCH_START: return "TRY_CATCH_START";
        case STATE::TRY_CATCH: return "TRY_CATCH";
        case STATE::TRY_CATCH_PARAM_START: return "TRY_CATCH_PARAM_START";
        case STATE::TRY_CATCH_PARAM: return "TRY_CATCH_PARAM";
        case STATE::TRY_CATCH_BODY_START: return "TRY_CATCH_BODY_START";
        case STATE::TRY_CATCH_BODY: return "TRY_CATCH_BODY";
        case STATE::TRY_FINALLY_START: return "TRY_FINALLY_START";
        case STATE::TRY_FINALLY: return "TRY_FINALLY";
        case STATE::TRY_FINALLY_BODY_START: return "TRY_FINALLY_BODY_START";
        case STATE::TRY_FINALLY_BODY: return "TRY_FINALLY_BODY";
        case STATE::FUNCTION_EXPRESSION_START: return "FUNCTION_EXPRESSION_START";
        case STATE::FUNCTION_EXPRESSION_PARAMETERS_START: return "FUNCTION_EXPRESSION_PARAMETERS_START";
        case STATE::FUNCTION_EXPRESSION_PARAMETER_NAME: return "FUNCTION_EXPRESSION_PARAMETER_NAME";
        case STATE::FUNCTION_EXPRESSION_PARAMETER_TYPE_ANNOTATION: return "FUNCTION_EXPRESSION_PARAMETER_TYPE_ANNOTATION";
        case STATE::FUNCTION_EXPRESSION_PARAMETER_DEFAULT_VALUE: return "FUNCTION_EXPRESSION_PARAMETER_DEFAULT_VALUE";
        case STATE::FUNCTION_EXPRESSION_PARAMETER_SEPARATOR: return "FUNCTION_EXPRESSION_PARAMETER_SEPARATOR";
        case STATE::FUNCTION_EXPRESSION_PARAMETERS_END: return "FUNCTION_EXPRESSION_PARAMETERS_END";
        case STATE::FUNCTION_EXPRESSION_RETURN_TYPE_ANNOTATION: return "FUNCTION_EXPRESSION_RETURN_TYPE_ANNOTATION";
        case STATE::FUNCTION_EXPRESSION_BODY_START: return "FUNCTION_EXPRESSION_BODY_START";
        case STATE::FUNCTION_EXPRESSION_BODY: return "FUNCTION_EXPRESSION_BODY";
        case STATE::BLOCK_I: return "I";
        case STATE::BLOCK_IN: return "IN";
        case STATE::BLOCK_INT: return "INT";
        case STATE::BLOCK_INTE: return "INTE";
        case STATE::BLOCK_INTER: return "INTER";
        case STATE::BLOCK_INTERF: return "INTERF";
        case STATE::BLOCK_INTERFA: return "INTERFA";
        case STATE::BLOCK_INTERFAC: return "INTERFAC";
        case STATE::BLOCK_INTERFACE: return "INTERFACE";
        case STATE::INTERFACE_DECLARATION_NAME: return "INTERFACE_DECLARATION_NAME";
        case STATE::INTERFACE_AFTER_NAME_START: return "INTERFACE_AFTER_NAME_START";
        case STATE::INTERFACE_AFTER_NAME_NAME: return "INTERFACE_AFTER_NAME_NAME";
        case STATE::INTERFACE_AFTER_NAME_SEPARATOR: return "INTERFACE_AFTER_NAME_SEPARATOR";
        case STATE::INTERFACE_BODY_START: return "INTERFACE_BODY_START";
        case STATE::INTERFACE_BODY: return "INTERFACE_BODY";
        case STATE::INTERFACE_PROPERTY_KEY: return "INTERFACE_PROPERTY_KEY";
        case STATE::INTERFACE_PROPERTY_TYPE: return "INTERFACE_PROPERTY_TYPE";
        case STATE::INTERFACE_PROPERTY_TYPE_NAME: return "INTERFACE_PROPERTY_TYPE_NAME";
        case STATE::INTERFACE_PROPERTY_TYPE_END: return "INTERFACE_PROPERTY_TYPE_END";
        case STATE::INTERFACE_PROPERTY_OPTIONAL: return "INTERFACE_PROPERTY_OPTIONAL";
        case STATE::INTERFACE_PROPERTY_READONLY: return "INTERFACE_PROPERTY_READONLY";
        case STATE::INTERFACE_METHOD_PARAMETERS_START: return "INTERFACE_METHOD_PARAMETERS_START";
        case STATE::INTERFACE_METHOD_PARAMETERS_END: return "INTERFACE_METHOD_PARAMETERS_END";
        case STATE::INTERFACE_METHOD_RETURN_TYPE: return "INTERFACE_METHOD_RETURN_TYPE";
        case STATE::INTERFACE_INDEX_SIGNATURE_START: return "INTERFACE_INDEX_SIGNATURE_START";
        case STATE::INTERFACE_INDEX_SIGNATURE_KEY: return "INTERFACE_INDEX_SIGNATURE_KEY";
        case STATE::INTERFACE_INDEX_SIGNATURE_KEY_NAME: return "INTERFACE_INDEX_SIGNATURE_KEY_NAME";
        case STATE::INTERFACE_INDEX_SIGNATURE_KEY_TYPE: return "INTERFACE_INDEX_SIGNATURE_KEY_TYPE";
        case STATE::INTERFACE_INDEX_SIGNATURE_KEY_TYPE_NAME: return "INTERFACE_INDEX_SIGNATURE_KEY_TYPE_NAME";
        case STATE::INTERFACE_INDEX_SIGNATURE_KEY_TYPE_END: return "INTERFACE_INDEX_SIGNATURE_KEY_TYPE_END";
        case STATE::INTERFACE_INDEX_SIGNATURE_VALUE_TYPE: return "INTERFACE_INDEX_SIGNATURE_VALUE_TYPE";
        case STATE::INTERFACE_INDEX_SIGNATURE_VALUE_TYPE_NAME: return "INTERFACE_INDEX_SIGNATURE_VALUE_TYPE_NAME";
        case STATE::INTERFACE_INDEX_SIGNATURE_VALUE_TYPE_END: return "INTERFACE_INDEX_SIGNATURE_VALUE_TYPE_END";
        case STATE::INTERFACE_INDEX_SIGNATURE_READONLY: return "INTERFACE_INDEX_SIGNATURE_READONLY";
        case STATE::INTERFACE_CALL_SIGNATURE_START: return "INTERFACE_CALL_SIGNATURE_START";
        case STATE::INTERFACE_CALL_SIGNATURE_PARAMETERS_START: return "INTERFACE_CALL_SIGNATURE_PARAMETERS_START";
        case STATE::INTERFACE_CALL_SIGNATURE_PARAMETERS_END: return "INTERFACE_CALL_SIGNATURE_PARAMETERS_END";
        case STATE::INTERFACE_CALL_SIGNATURE_RETURN_TYPE: return "INTERFACE_CALL_SIGNATURE_RETURN_TYPE";
        case STATE::INTERFACE_CONSTRUCT_SIGNATURE_START: return "INTERFACE_CONSTRUCT_SIGNATURE_START";
        case STATE::INTERFACE_CONSTRUCT_SIGNATURE_PARAMETERS_START: return "INTERFACE_CONSTRUCT_SIGNATURE_PARAMETERS_START";
        case STATE::INTERFACE_CONSTRUCT_SIGNATURE_PARAMETERS_END: return "INTERFACE_CONSTRUCT_SIGNATURE_PARAMETERS_END";
        case STATE::INTERFACE_CONSTRUCT_SIGNATURE_RETURN_TYPE: return "INTERFACE_CONSTRUCT_SIGNATURE_RETURN_TYPE";
        case STATE::BLOCK_CL: return "CL";
        case STATE::BLOCK_CLA: return "CLA";
        case STATE::BLOCK_CLAS: return "CLAS";
        case STATE::BLOCK_CLASS: return "CLASS";
        case STATE::CLASS_DECLARATION_NAME: return "CLASS_DECLARATION_NAME";
        case STATE::CLASS_AFTER_NAME_START: return "CLASS_AFTER_NAME_START";
        case STATE::CLASS_AFTER_NAME_NAME: return "CLASS_AFTER_NAME_NAME";
        case STATE::CLASS_IMPLEMENTS_START: return "CLASS_IMPLEMENTS_START";
        case STATE::CLASS_IMPLEMENTS_NAME: return "CLASS_IMPLEMENTS_NAME";
        case STATE::CLASS_IMPLEMENTS_SEPARATOR: return "CLASS_IMPLEMENTS_SEPARATOR";
        case STATE::CLASS_BODY_START: return "CLASS_BODY_START";
        case STATE::CLASS_BODY: return "CLASS_BODY";
        case STATE::CLASS_STATIC_START: return "CLASS_STATIC_START";
        case STATE::CLASS_PROPERTY_KEY: return "CLASS_PROPERTY_KEY";
        case STATE::CLASS_PROPERTY_TYPE: return "CLASS_PROPERTY_TYPE";
        case STATE::CLASS_PROPERTY_INITIALIZER: return "CLASS_PROPERTY_INITIALIZER";
        case STATE::CLASS_METHOD_PARAMETERS_START: return "CLASS_METHOD_PARAMETERS_START";
        case STATE::CLASS_METHOD_PARAMETERS_END: return "CLASS_METHOD_PARAMETERS_END";
        case STATE::CLASS_METHOD_RETURN_TYPE: return "CLASS_METHOD_RETURN_TYPE";
        case STATE::CLASS_METHOD_BODY_START: return "CLASS_METHOD_BODY_START";
        case STATE::CLASS_METHOD_BODY: return "CLASS_METHOD_BODY";
        // New class feature states
        case STATE::CLASS_ACCESS_MODIFIER_PUBLIC: return "CLASS_ACCESS_MODIFIER_PUBLIC";
        case STATE::CLASS_ACCESS_MODIFIER_PRIVATE: return "CLASS_ACCESS_MODIFIER_PRIVATE";
        case STATE::CLASS_ACCESS_MODIFIER_PROTECTED: return "CLASS_ACCESS_MODIFIER_PROTECTED";
        case STATE::CLASS_READONLY_MODIFIER: return "CLASS_READONLY_MODIFIER";
        case STATE::CLASS_ABSTRACT_MODIFIER: return "CLASS_ABSTRACT_MODIFIER";
        case STATE::CLASS_GETTER_START: return "CLASS_GETTER_START";
        case STATE::CLASS_SETTER_START: return "CLASS_SETTER_START";
        case STATE::CLASS_GETTER_NAME: return "CLASS_GETTER_NAME";
        case STATE::CLASS_SETTER_NAME: return "CLASS_SETTER_NAME";
        case STATE::CLASS_GETTER_PARAMETERS_START: return "CLASS_GETTER_PARAMETERS_START";
        case STATE::CLASS_SETTER_PARAMETERS_START: return "CLASS_SETTER_PARAMETERS_START";
        case STATE::CLASS_GETTER_BODY_START: return "CLASS_GETTER_BODY_START";
        case STATE::CLASS_SETTER_BODY_START: return "CLASS_SETTER_BODY_START";
        case STATE::CLASS_GETTER_BODY: return "CLASS_GETTER_BODY";
        case STATE::CLASS_SETTER_BODY: return "CLASS_SETTER_BODY";
        // Generic type states
        case STATE::TYPE_GENERIC_PARAMETERS_START: return "TYPE_GENERIC_PARAMETERS_START";
        case STATE::TYPE_GENERIC_PARAMETER_NAME: return "TYPE_GENERIC_PARAMETER_NAME";
        case STATE::TYPE_GENERIC_PARAMETER_SEPARATOR: return "TYPE_GENERIC_PARAMETER_SEPARATOR";
        case STATE::TYPE_GENERIC_PARAMETERS_END: return "TYPE_GENERIC_PARAMETERS_END";
        case STATE::TYPE_GENERIC_TYPE_START: return "TYPE_GENERIC_TYPE_START";
        case STATE::TYPE_GENERIC_TYPE_ARGUMENTS: return "TYPE_GENERIC_TYPE_ARGUMENTS";
        // Interface generic states
        case STATE::INTERFACE_GENERIC_PARAMETERS_START: return "INTERFACE_GENERIC_PARAMETERS_START";
        case STATE::INTERFACE_GENERIC_PARAMETER_NAME: return "INTERFACE_GENERIC_PARAMETER_NAME";
        case STATE::INTERFACE_GENERIC_PARAMETER_SEPARATOR: return "INTERFACE_GENERIC_PARAMETER_SEPARATOR";
        case STATE::INTERFACE_GENERIC_PARAMETERS_END: return "INTERFACE_GENERIC_PARAMETERS_END";
        // Class generic states
        case STATE::CLASS_GENERIC_PARAMETERS_START: return "CLASS_GENERIC_PARAMETERS_START";
        case STATE::CLASS_GENERIC_PARAMETER_NAME: return "CLASS_GENERIC_PARAMETER_NAME";
        case STATE::CLASS_GENERIC_PARAMETER_SEPARATOR: return "CLASS_GENERIC_PARAMETER_SEPARATOR";
        case STATE::CLASS_GENERIC_PARAMETERS_END: return "CLASS_GENERIC_PARAMETERS_END";
        // Function generic states
        case STATE::FUNCTION_GENERIC_PARAMETERS_START: return "FUNCTION_GENERIC_PARAMETERS_START";
        case STATE::FUNCTION_GENERIC_PARAMETER_NAME: return "FUNCTION_GENERIC_PARAMETER_NAME";
        case STATE::FUNCTION_GENERIC_PARAMETER_SEPARATOR: return "FUNCTION_GENERIC_PARAMETER_SEPARATOR";
        case STATE::FUNCTION_GENERIC_PARAMETERS_END: return "FUNCTION_GENERIC_PARAMETERS_END";
        // Module import/export states
        case STATE::BLOCK_IM: return "IM";
        case STATE::BLOCK_IMP: return "IMP";
        case STATE::BLOCK_IMPO: return "IMPO";
        case STATE::BLOCK_IMPOR: return "IMPOR";
        case STATE::BLOCK_IMPORT: return "IMPORT";
        case STATE::IMPORT_SPECIFIERS_START: return "IMPORT_SPECIFIERS_START";
        case STATE::IMPORT_SPECIFIER_NAME: return "IMPORT_SPECIFIER_NAME";
        case STATE::IMPORT_SPECIFIER_LOCAL_NAME: return "IMPORT_SPECIFIER_LOCAL_NAME";
        case STATE::IMPORT_SPECIFIER_SEPARATOR: return "IMPORT_SPECIFIER_SEPARATOR";
        case STATE::IMPORT_SPECIFIERS_END: return "IMPORT_SPECIFIERS_END";
        case STATE::IMPORT_FROM: return "IMPORT_FROM";
        case STATE::IMPORT_SOURCE_START: return "IMPORT_SOURCE_START";
        case STATE::IMPORT_SOURCE: return "IMPORT_SOURCE";
        case STATE::IMPORT_SOURCE_END: return "IMPORT_SOURCE_END";
        case STATE::BLOCK_EX: return "EX";
        case STATE::BLOCK_EXP: return "EXP";
        case STATE::BLOCK_EXPO: return "EXPO";
        case STATE::BLOCK_EXPOR: return "EXPOR";
        case STATE::BLOCK_EXPORT: return "EXPORT";
        case STATE::EXPORT_SPECIFIERS_START: return "EXPORT_SPECIFIERS_START";
        case STATE::EXPORT_SPECIFIER_NAME: return "EXPORT_SPECIFIER_NAME";
        case STATE::EXPORT_SPECIFIER_AS: return "EXPORT_SPECIFIER_AS";
        case STATE::EXPORT_SPECIFIER_EXPORTED_NAME: return "EXPORT_SPECIFIER_EXPORTED_NAME";
        case STATE::EXPORT_SPECIFIER_SEPARATOR: return "EXPORT_SPECIFIER_SEPARATOR";
        case STATE::EXPORT_SPECIFIERS_END: return "EXPORT_SPECIFIERS_END";
        case STATE::EXPORT_FROM: return "EXPORT_FROM";
        case STATE::EXPORT_SOURCE_START: return "EXPORT_SOURCE_START";
        case STATE::EXPORT_SOURCE: return "EXPORT_SOURCE";
        case STATE::EXPORT_SOURCE_END: return "EXPORT_SOURCE_END";
        case STATE::EXPORT_DEFAULT: return "EXPORT_DEFAULT";
        case STATE::EXPORT_ALL: return "EXPORT_ALL";
        case STATE::EXPORT_DECLARATION: return "EXPORT_DECLARATION";
        // Async/await states
        case STATE::BLOCK_A: return "A";
        case STATE::BLOCK_AS: return "AS";
        case STATE::BLOCK_ASY: return "ASY";
        case STATE::BLOCK_ASYN: return "ASYN";
        case STATE::BLOCK_ASYNC: return "ASYNC";
        case STATE::BLOCK_AW: return "AW";
        case STATE::BLOCK_AWA: return "AWA";
        case STATE::BLOCK_AWAI: return "AWAI";
        case STATE::BLOCK_AWAIT: return "AWAIT";
        case STATE::EXPRESSION_AWAIT: return "EXPRESSION_AWAIT";
        // Enum states
        case STATE::BLOCK_ENUM_E: return "BLOCK_ENUM_E";
        case STATE::BLOCK_ENUM_EN: return "BLOCK_ENUM_EN";
        case STATE::BLOCK_ENUM_ENU: return "BLOCK_ENUM_ENU";
        case STATE::ENUM_DECLARATION_NAME: return "ENUM_DECLARATION_NAME";
        case STATE::ENUM_BODY_START: return "ENUM_BODY_START";
        case STATE::ENUM_BODY: return "ENUM_BODY";
        case STATE::ENUM_MEMBER_NAME: return "ENUM_MEMBER_NAME";
        case STATE::ENUM_MEMBER_INITIALIZER: return "ENUM_MEMBER_INITIALIZER";
        case STATE::ENUM_MEMBER_SEPARATOR: return "ENUM_MEMBER_SEPARATOR";
        // Type alias states
        case STATE::BLOCK_TY: return "TY";
        case STATE::BLOCK_TYP: return "TYP";
        case STATE::BLOCK_TYPE: return "TYPE";
        case STATE::TYPE_ALIAS_NAME: return "TYPE_ALIAS_NAME";
        case STATE::TYPE_ALIAS_GENERIC_PARAMETERS_START: return "TYPE_ALIAS_GENERIC_PARAMETERS_START";
        case STATE::TYPE_ALIAS_GENERIC_PARAMETER_NAME: return "TYPE_ALIAS_GENERIC_PARAMETER_NAME";
        case STATE::TYPE_ALIAS_GENERIC_PARAMETER_SEPARATOR: return "TYPE_ALIAS_GENERIC_PARAMETER_SEPARATOR";
        case STATE::TYPE_ALIAS_GENERIC_PARAMETERS_END: return "TYPE_ALIAS_GENERIC_PARAMETERS_END";
        case STATE::TYPE_ALIAS_EQUALS: return "TYPE_ALIAS_EQUALS";
        case STATE::TYPE_ALIAS_TYPE: return "TYPE_ALIAS_TYPE";
        // Advanced generics states
        case STATE::TYPE_CONDITIONAL_CHECK: return "TYPE_CONDITIONAL_CHECK";
        case STATE::TYPE_CONDITIONAL_E: return "TYPE_CONDITIONAL_E";
        case STATE::TYPE_CONDITIONAL_EX: return "TYPE_CONDITIONAL_EX";
        case STATE::TYPE_CONDITIONAL_EXT: return "TYPE_CONDITIONAL_EXT";
        case STATE::TYPE_CONDITIONAL_EXTE: return "TYPE_CONDITIONAL_EXTE";
        case STATE::TYPE_CONDITIONAL_EXTEN: return "TYPE_CONDITIONAL_EXTEN";
        case STATE::TYPE_CONDITIONAL_EXTEND: return "TYPE_CONDITIONAL_EXTEND";
        case STATE::TYPE_CONDITIONAL_EXTENDS: return "TYPE_CONDITIONAL_EXTENDS";
        case STATE::TYPE_CONDITIONAL_TRUE: return "TYPE_CONDITIONAL_TRUE";
        case STATE::TYPE_CONDITIONAL_FALSE: return "TYPE_CONDITIONAL_FALSE";
        case STATE::TYPE_CONDITIONAL_QUESTION: return "TYPE_CONDITIONAL_QUESTION";
        case STATE::TYPE_INFER_I: return "TYPE_INFER_I";
        case STATE::TYPE_INFER_IN: return "TYPE_INFER_IN";
        case STATE::TYPE_INFER_INF: return "TYPE_INFER_INF";
        case STATE::TYPE_INFER_INFE: return "TYPE_INFER_INFE";
        case STATE::TYPE_INFER_INFER: return "TYPE_INFER_INFER";
        case STATE::TYPE_INFER_START: return "TYPE_INFER_START";
        case STATE::TYPE_INFER_NAME: return "TYPE_INFER_NAME";
        case STATE::TYPE_TEMPLATE_LITERAL_START: return "TYPE_TEMPLATE_LITERAL_START";
        case STATE::TYPE_TEMPLATE_LITERAL_QUASI: return "TYPE_TEMPLATE_LITERAL_QUASI";
        case STATE::TYPE_TEMPLATE_LITERAL_INTERPOLATION: return "TYPE_TEMPLATE_LITERAL_INTERPOLATION";
        case STATE::TYPE_MAPPED_START: return "TYPE_MAPPED_START";
        case STATE::TYPE_MAPPED_R: return "TYPE_MAPPED_R";
        case STATE::TYPE_MAPPED_RE: return "TYPE_MAPPED_RE";
        case STATE::TYPE_MAPPED_REA: return "TYPE_MAPPED_REA";
        case STATE::TYPE_MAPPED_READ: return "TYPE_MAPPED_READ";
        case STATE::TYPE_MAPPED_READO: return "TYPE_MAPPED_READO";
        case STATE::TYPE_MAPPED_READON: return "TYPE_MAPPED_READON";
        case STATE::TYPE_MAPPED_READONL: return "TYPE_MAPPED_READONL";
        case STATE::TYPE_MAPPED_READONLY: return "TYPE_MAPPED_READONLY";
        case STATE::TYPE_MAPPED_PARAMETER: return "TYPE_MAPPED_PARAMETER";
        case STATE::TYPE_MAPPED_I: return "TYPE_MAPPED_I";
        case STATE::TYPE_MAPPED_IN: return "TYPE_MAPPED_IN";
        case STATE::TYPE_MAPPED_IN_CONSTRAINT: return "TYPE_MAPPED_IN_CONSTRAINT";
        case STATE::TYPE_MAPPED_CONSTRAINT: return "TYPE_MAPPED_CONSTRAINT";
        case STATE::TYPE_MAPPED_A: return "TYPE_MAPPED_A";
        case STATE::TYPE_MAPPED_AS: return "TYPE_MAPPED_AS";
        case STATE::TYPE_MAPPED_AS_NAME: return "TYPE_MAPPED_AS_NAME";
        case STATE::TYPE_MAPPED_VALUE: return "TYPE_MAPPED_VALUE";
        case STATE::TYPE_MAPPED_OPTIONAL: return "TYPE_MAPPED_OPTIONAL";
        // Interface after name states
        case STATE::INTERFACE_AFTER_NAME_E: return "INTERFACE_AFTER_NAME_E";
        case STATE::INTERFACE_AFTER_NAME_EX: return "INTERFACE_AFTER_NAME_EX";
        case STATE::INTERFACE_AFTER_NAME_EXT: return "INTERFACE_AFTER_NAME_EXT";
        case STATE::INTERFACE_AFTER_NAME_EXTE: return "INTERFACE_AFTER_NAME_EXTE";
        case STATE::INTERFACE_AFTER_NAME_EXTEN: return "INTERFACE_AFTER_NAME_EXTEN";
        case STATE::INTERFACE_AFTER_NAME_EXTEND: return "INTERFACE_AFTER_NAME_EXTEND";
        case STATE::INTERFACE_AFTER_NAME_EXTENDS: return "INTERFACE_AFTER_NAME_EXTENDS";
        // Interface member modifier states
        case STATE::INTERFACE_MEMBER_R: return "INTERFACE_MEMBER_R";
        case STATE::INTERFACE_MEMBER_RE: return "INTERFACE_MEMBER_RE";
        case STATE::INTERFACE_MEMBER_REA: return "INTERFACE_MEMBER_REA";
        case STATE::INTERFACE_MEMBER_READ: return "INTERFACE_MEMBER_READ";
        case STATE::INTERFACE_MEMBER_READO: return "INTERFACE_MEMBER_READO";
        case STATE::INTERFACE_MEMBER_READON: return "INTERFACE_MEMBER_READON";
        case STATE::INTERFACE_MEMBER_READONL: return "INTERFACE_MEMBER_READONL";
        case STATE::INTERFACE_MEMBER_READONLY: return "INTERFACE_MEMBER_READONLY";
        // Interface member "new" keyword states
        case STATE::INTERFACE_MEMBER_N: return "INTERFACE_MEMBER_N";
        case STATE::INTERFACE_MEMBER_NE: return "INTERFACE_MEMBER_NE";
        case STATE::INTERFACE_MEMBER_NEW: return "INTERFACE_MEMBER_NEW";
        // Class after name states
        case STATE::CLASS_AFTER_NAME_E: return "CLASS_AFTER_NAME_E";
        case STATE::CLASS_AFTER_NAME_EX: return "CLASS_AFTER_NAME_EX";
        case STATE::CLASS_AFTER_NAME_EXT: return "CLASS_AFTER_NAME_EXT";
        case STATE::CLASS_AFTER_NAME_EXTE: return "CLASS_AFTER_NAME_EXTE";
        case STATE::CLASS_AFTER_NAME_EXTEN: return "CLASS_AFTER_NAME_EXTEN";
        case STATE::CLASS_AFTER_NAME_EXTEND: return "CLASS_AFTER_NAME_EXTEND";
        case STATE::CLASS_AFTER_NAME_EXTENDS: return "CLASS_AFTER_NAME_EXTENDS";
        // Class inheritance identifier states
        case STATE::CLASS_INHERITANCE_I: return "CLASS_INHERITANCE_I";
        case STATE::CLASS_INHERITANCE_IM: return "CLASS_INHERITANCE_IM";
        case STATE::CLASS_INHERITANCE_IMP: return "CLASS_INHERITANCE_IMP";
        case STATE::CLASS_INHERITANCE_IMPL: return "CLASS_INHERITANCE_IMPL";
        case STATE::CLASS_INHERITANCE_IMPLE: return "CLASS_INHERITANCE_IMPLE";
        case STATE::CLASS_INHERITANCE_IMPLEM: return "CLASS_INHERITANCE_IMPLEM";
        case STATE::CLASS_INHERITANCE_IMPLEME: return "CLASS_INHERITANCE_IMPLEME";
        case STATE::CLASS_INHERITANCE_IMPLEMEN: return "CLASS_INHERITANCE_IMPLEMEN";
        case STATE::CLASS_INHERITANCE_IMPLEMENTS: return "CLASS_INHERITANCE_IMPLEMENTS";
        // Module import/export keyword states
        case STATE::POST_IMPORT_SPECIFIER_A: return "POST_IMPORT_SPECIFIER_A";
        case STATE::IMPORT_SPECIFIER_AFTER_AS: return "IMPORT_SPECIFIER_AFTER_AS";
        case STATE::IMPORT_SPECIFIER_AS: return "IMPORT_SPECIFIER_AS";
        case STATE::IMPORT_FROM_F: return "IMPORT_FROM_F";
        case STATE::IMPORT_FROM_FR: return "IMPORT_FROM_FR";
        case STATE::IMPORT_FROM_FRO: return "IMPORT_FROM_FRO";
        case STATE::IMPORT_FROM_FROM: return "IMPORT_FROM_FROM";
        case STATE::EXPORT_A: return "EXPORT_A";
        case STATE::EXPORT_AS: return "EXPORT_AS";
        case STATE::EXPORT_AS_A: return "EXPORT_AS_A";
        case STATE::EXPORT_SPECIFIER_AFTER_AS: return "EXPORT_SPECIFIER_AFTER_AS";
        case STATE::EXPORT_FROM_F: return "EXPORT_FROM_F";
        case STATE::EXPORT_FROM_FR: return "EXPORT_FROM_FR";
        case STATE::EXPORT_FROM_FRO: return "EXPORT_FROM_FRO";
        case STATE::EXPORT_FROM_FROM: return "EXPORT_FROM_FROM";
        case STATE::EXPORT_DEFAULT_D: return "EXPORT_DEFAULT_D";
        case STATE::EXPORT_DEFAULT_DE: return "EXPORT_DEFAULT_DE";
        case STATE::EXPORT_DEFAULT_DEF: return "EXPORT_DEFAULT_DEF";
        case STATE::EXPORT_DEFAULT_DEFA: return "EXPORT_DEFAULT_DEFA";
        case STATE::EXPORT_DEFAULT_DEFAU: return "EXPORT_DEFAULT_DEFAU";
        case STATE::EXPORT_DEFAULT_DEFAUL: return "EXPORT_DEFAULT_DEFAUL";
        case STATE::EXPORT_DEFAULT_DEFAULT: return "EXPORT_DEFAULT_DEFAULT";

        case STATE::EXPORT_V: return "EXPORT_V";
        case STATE::EXPORT_VA: return "EXPORT_VA";
        case STATE::EXPORT_VAR: return "EXPORT_VAR";
        case STATE::EXPORT_F: return "EXPORT_F";
        case STATE::EXPORT_FU: return "EXPORT_FU";
        case STATE::EXPORT_FUN: return "EXPORT_FUN";
        case STATE::EXPORT_FUNC: return "EXPORT_FUNC";
        case STATE::EXPORT_FUNCT: return "EXPORT_FUNCT";
        case STATE::EXPORT_FUNCTI: return "EXPORT_FUNCTI";
        case STATE::EXPORT_FUNCTIO: return "EXPORT_FUNCTIO";
        case STATE::EXPORT_FUNCTION: return "EXPORT_FUNCTION";
        case STATE::EXPORT_IDENTIFIER: return "EXPORT_IDENTIFIER";

        // TechnoScript specific features
        case STATE::BLOCK_P: return "P";
        case STATE::BLOCK_PR: return "PR";
        case STATE::BLOCK_PRI: return "PRI";
        case STATE::BLOCK_PRIN: return "PRIN";
        case STATE::BLOCK_PRINT: return "PRINT";
        case STATE::BLOCK_G: return "G";
        case STATE::BLOCK_GO: return "GO";
        case STATE::BLOCK_SE: return "SE";
        case STATE::BLOCK_SET: return "SET";
        case STATE::BLOCK_SETT: return "SETT";
        case STATE::BLOCK_SETTI: return "SETTI";
        case STATE::BLOCK_SETTIM: return "SETTIM";
        case STATE::BLOCK_SETTIMEO: return "SETTIMEO";
        case STATE::BLOCK_SETTIMEOU: return "SETTIMEOU";
        case STATE::BLOCK_SETTIMEOUT: return "SETTIMEOUT";
        case STATE::BLOCK_SL: return "SL";
        case STATE::BLOCK_SLE: return "SLE";
        case STATE::BLOCK_SLEE: return "SLEE";
        case STATE::BLOCK_SLEEP: return "SLEEP";
        case STATE::BLOCK_R: return "R";
        case STATE::BLOCK_RA: return "RA";
        case STATE::BLOCK_RAW: return "RAW";
        case STATE::BLOCK_RAWM: return "RAWM";
        case STATE::BLOCK_RAWME: return "RAWME";
        case STATE::BLOCK_RAWMEM: return "RAWMEM";
        case STATE::BLOCK_RAWMEMO: return "RAWMEMO";
        case STATE::BLOCK_RAWMEMOR: return "RAWMEMOR";
        case STATE::BLOCK_RAWMEMORY: return "RAWMEMORY";
        case STATE::BLOCK_TH: return "TH";
        case STATE::BLOCK_THI: return "THI";
        case STATE::BLOCK_THIS: return "THIS";
        case STATE::BLOCK_N: return "N";
        case STATE::BLOCK_NE: return "NE";
        case STATE::BLOCK_NEW: return "NEW";
        case STATE::EXPRESSION_MEMBER_ACCESS: return "EXPRESSION_MEMBER_ACCESS";
        case STATE::EXPRESSION_METHOD_CALL: return "EXPRESSION_METHOD_CALL";
        case STATE::EXPRESSION_BRACKET_ACCESS: return "EXPRESSION_BRACKET_ACCESS";
        case STATE::EXPRESSION_NEW: return "EXPRESSION_NEW";
        case STATE::EXPRESSION_THIS: return "EXPRESSION_THIS";
        case STATE::EXPRESSION_INCREMENT: return "EXPRESSION_INCREMENT";
        case STATE::STATEMENT_PRINT: return "STATEMENT_PRINT";
        case STATE::STATEMENT_GO: return "STATEMENT_GO";
        case STATE::STATEMENT_SETTIMEOUT: return "STATEMENT_SETTIMEOUT";
        case STATE::STATEMENT_SLEEP: return "STATEMENT_SLEEP";
    }
    return "UNKNOWN_STATE";
}
