#pragma once

enum class STATE {
    NONE,
    NONE_V,
    NONE_VA,
    NONE_VAR,
    NONE_C,
    NONE_CO,
    NONE_CON,
    NONE_CONS,
    NONE_CONST,
    NONE_L,
    NONE_LE,
    NONE_LET,
    EXPECT_IDENTIFIER,
    IDENTIFIER_NAME,
    IDENTIFIER_COMPLETE,
    EXPECT_TYPE_ANNOTATION,
    TYPE_ANNOTATION,
    EXPECT_EQUALS,
    EXPRESSION_EXPECT_OPERAND,
    EXPRESSION_AFTER_OPERAND,
    EXPRESSION_AFTER_OPERAND_NEW_LINE,
    EXPRESSION_NUMBER,
    EXPRESSION_IDENTIFIER,
    EXPRESSION_SINGLE_QUOTE,
    EXPRESSION_SINGLE_QUOTE_ESCAPE,
    EXPRESSION_DOUBLE_QUOTE,
    EXPRESSION_DOUBLE_QUOTE_ESCAPE,
    EXPRESSION_PLUS,
    EXPRESSION_MINUS,
    EXPECT_IMMEDIATE_IDENTIFIER,
    VARIABLE_CREATE_IDENTIFIER_COMPLETE
};

inline const char* stateToString(STATE state) {
    switch (state) {
        case STATE::NONE: return "NONE";
        case STATE::NONE_V: return "V";
        case STATE::NONE_VA: return "VA";
        case STATE::NONE_VAR: return "VAR";
        case STATE::NONE_C: return "C";
        case STATE::NONE_CO: return "CO";
        case STATE::NONE_CON: return "CON";
        case STATE::NONE_CONS: return "CONS";
        case STATE::NONE_CONST: return "CONST";
        case STATE::NONE_L: return "L";
        case STATE::NONE_LE: return "LE";
        case STATE::NONE_LET: return "LET";
        case STATE::EXPECT_IDENTIFIER: return "AWAIT_IDENTIFIER";
        case STATE::IDENTIFIER_NAME: return "IDENTIFIER_NAME";
        case STATE::IDENTIFIER_COMPLETE: return "IDENTIFIER_COMPLETE";
        case STATE::EXPECT_TYPE_ANNOTATION: return "AWAIT_TYPE_ANNOTATION";
        case STATE::TYPE_ANNOTATION: return "TYPE_ANNOTATION";
        case STATE::EXPECT_EQUALS: return "AWAIT_EQUALS";
        case STATE::EXPRESSION_EXPECT_OPERAND: return "EXPRESSION_EXPECT_OPERAND";
        case STATE::EXPRESSION_AFTER_OPERAND: return "EXPRESSION_AFTER_OPERAND";
        case STATE::EXPRESSION_AFTER_OPERAND_NEW_LINE: return "EXPRESSION_AFTER_OPERAND_NEW_LINE";
        case STATE::EXPRESSION_NUMBER: return "EXPRESSION_NUMBER";
        case STATE::EXPRESSION_IDENTIFIER: return "EXPRESSION_IDENTIFIER";
        case STATE::EXPRESSION_SINGLE_QUOTE: return "EXPRESSION_SINGLE_QUOTE";
        case STATE::EXPRESSION_SINGLE_QUOTE_ESCAPE: return "EXPRESSION_SINGLE_QUOTE_ESCAPE";
        case STATE::EXPRESSION_DOUBLE_QUOTE: return "EXPRESSION_DOUBLE_QUOTE";
        case STATE::EXPRESSION_DOUBLE_QUOTE_ESCAPE: return "EXPRESSION_DOUBLE_QUOTE_ESCAPE";
        case STATE::EXPRESSION_PLUS: return "EXPRESSION_PLUS";
        case STATE::EXPRESSION_MINUS: return "EXPRESSION_MINUS";
        case STATE::EXPECT_IMMEDIATE_IDENTIFIER: return "EXPECT_IMMEDIATE_IDENTIFIER";
        case STATE::VARIABLE_CREATE_IDENTIFIER_COMPLETE: return "VARIABLE_CREATE_IDENTIFIER_COMPLETE";
    }
    return "UNKNOWN_STATE";
}
