#pragma once

enum class STATE {
    NONE,
    NONE_V,
    NONE_VA,
    NONE_VAR,
    NONE_C,
    NONE_CO,
    NONE_CON,
    NONE_CONS,
    NONE_CONST,
    NONE_L,
    NONE_LE,
    NONE_LET,
    NONE_F,
    NONE_I,
    EXPECT_IDENTIFIER,
    IDENTIFIER_NAME,
    IDENTIFIER_COMPLETE,
    EXPECT_TYPE_ANNOTATION,
    TYPE_ANNOTATION,
    EXPECT_EQUALS,
    EXPRESSION_EXPECT_OPERAND,
    EXPRESSION_AFTER_OPERAND,
    EXPRESSION_AFTER_OPERAND_NEW_LINE,
    EXPRESSION_NUMBER,
    EXPRESSION_IDENTIFIER,
    EXPRESSION_SINGLE_QUOTE,
    EXPRESSION_SINGLE_QUOTE_ESCAPE,
    EXPRESSION_DOUBLE_QUOTE,
    EXPRESSION_DOUBLE_QUOTE_ESCAPE,
    EXPRESSION_PLUS,
    EXPRESSION_MINUS,
    EXPECT_IMMEDIATE_IDENTIFIER,
    VARIABLE_CREATE_IDENTIFIER_COMPLETE,
    FUNCTION_DECLARATION_NAME,
    FUNCTION_PARAMETERS_START,
    FUNCTION_PARAMETER_NAME,
    FUNCTION_PARAMETER_TYPE_ANNOTATION,
    FUNCTION_PARAMETER_DEFAULT_VALUE,
    FUNCTION_PARAMETER_SEPARATOR,
    FUNCTION_PARAMETERS_END,
    FUNCTION_RETURN_TYPE_ANNOTATION,
    FUNCTION_BODY_START,
    FUNCTION_BODY,
    ARROW_FUNCTION_PARAMETERS,
    ARROW_FUNCTION_ARROW,
    ARROW_FUNCTION_BODY,
    ARRAY_LITERAL_START,
    ARRAY_LITERAL_ELEMENT,
    ARRAY_LITERAL_SEPARATOR,
    OBJECT_LITERAL_START,
    OBJECT_LITERAL_PROPERTY_KEY,
    OBJECT_LITERAL_PROPERTY_COLON,
    OBJECT_LITERAL_PROPERTY_VALUE,
    OBJECT_LITERAL_SEPARATOR,
    IF_CONDITION_START,
    IF_CONSEQUENT,
    IF_ALTERNATE_START,
    IF_ALTERNATE,
    BLOCK_STATEMENT_START,
    BLOCK_STATEMENT_BODY,
    NONE_W,
    NONE_WH,
    NONE_WHI,
    NONE_WHIL,
    NONE_WHILE,
    WHILE_CONDITION_START,
    WHILE_BODY
};

inline const char* stateToString(STATE state) {
    switch (state) {
        case STATE::NONE: return "NONE";
        case STATE::NONE_V: return "V";
        case STATE::NONE_VA: return "VA";
        case STATE::NONE_VAR: return "VAR";
        case STATE::NONE_C: return "C";
        case STATE::NONE_CO: return "CO";
        case STATE::NONE_CON: return "CON";
        case STATE::NONE_CONS: return "CONS";
        case STATE::NONE_CONST: return "CONST";
        case STATE::NONE_L: return "L";
        case STATE::NONE_LE: return "LE";
        case STATE::NONE_LET: return "LET";
        case STATE::EXPECT_IDENTIFIER: return "AWAIT_IDENTIFIER";
        case STATE::IDENTIFIER_NAME: return "IDENTIFIER_NAME";
        case STATE::IDENTIFIER_COMPLETE: return "IDENTIFIER_COMPLETE";
        case STATE::EXPECT_TYPE_ANNOTATION: return "AWAIT_TYPE_ANNOTATION";
        case STATE::TYPE_ANNOTATION: return "TYPE_ANNOTATION";
        case STATE::EXPECT_EQUALS: return "AWAIT_EQUALS";
        case STATE::EXPRESSION_EXPECT_OPERAND: return "EXPRESSION_EXPECT_OPERAND";
        case STATE::EXPRESSION_AFTER_OPERAND: return "EXPRESSION_AFTER_OPERAND";
        case STATE::EXPRESSION_AFTER_OPERAND_NEW_LINE: return "EXPRESSION_AFTER_OPERAND_NEW_LINE";
        case STATE::EXPRESSION_NUMBER: return "EXPRESSION_NUMBER";
        case STATE::EXPRESSION_IDENTIFIER: return "EXPRESSION_IDENTIFIER";
        case STATE::EXPRESSION_SINGLE_QUOTE: return "EXPRESSION_SINGLE_QUOTE";
        case STATE::EXPRESSION_SINGLE_QUOTE_ESCAPE: return "EXPRESSION_SINGLE_QUOTE_ESCAPE";
        case STATE::EXPRESSION_DOUBLE_QUOTE: return "EXPRESSION_DOUBLE_QUOTE";
        case STATE::EXPRESSION_DOUBLE_QUOTE_ESCAPE: return "EXPRESSION_DOUBLE_QUOTE_ESCAPE";
        case STATE::EXPRESSION_PLUS: return "EXPRESSION_PLUS";
        case STATE::EXPRESSION_MINUS: return "EXPRESSION_MINUS";
        case STATE::EXPECT_IMMEDIATE_IDENTIFIER: return "EXPECT_IMMEDIATE_IDENTIFIER";
        case STATE::VARIABLE_CREATE_IDENTIFIER_COMPLETE: return "VARIABLE_CREATE_IDENTIFIER_COMPLETE";
        case STATE::NONE_F: return "F";
        case STATE::NONE_I: return "I";
        case STATE::FUNCTION_DECLARATION_NAME: return "FUNCTION_DECLARATION_NAME";
        case STATE::FUNCTION_PARAMETERS_START: return "FUNCTION_PARAMETERS_START";
        case STATE::FUNCTION_PARAMETER_NAME: return "FUNCTION_PARAMETER_NAME";
        case STATE::FUNCTION_PARAMETER_TYPE_ANNOTATION: return "FUNCTION_PARAMETER_TYPE_ANNOTATION";
        case STATE::FUNCTION_PARAMETER_DEFAULT_VALUE: return "FUNCTION_PARAMETER_DEFAULT_VALUE";
        case STATE::FUNCTION_PARAMETER_SEPARATOR: return "FUNCTION_PARAMETER_SEPARATOR";
        case STATE::FUNCTION_PARAMETERS_END: return "FUNCTION_PARAMETERS_END";
        case STATE::FUNCTION_RETURN_TYPE_ANNOTATION: return "FUNCTION_RETURN_TYPE_ANNOTATION";
        case STATE::FUNCTION_BODY_START: return "FUNCTION_BODY_START";
        case STATE::FUNCTION_BODY: return "FUNCTION_BODY";
        case STATE::ARROW_FUNCTION_PARAMETERS: return "ARROW_FUNCTION_PARAMETERS";
        case STATE::ARROW_FUNCTION_ARROW: return "ARROW_FUNCTION_ARROW";
        case STATE::ARROW_FUNCTION_BODY: return "ARROW_FUNCTION_BODY";
        case STATE::ARRAY_LITERAL_START: return "ARRAY_LITERAL_START";
        case STATE::ARRAY_LITERAL_ELEMENT: return "ARRAY_LITERAL_ELEMENT";
        case STATE::ARRAY_LITERAL_SEPARATOR: return "ARRAY_LITERAL_SEPARATOR";
        case STATE::OBJECT_LITERAL_START: return "OBJECT_LITERAL_START";
        case STATE::OBJECT_LITERAL_PROPERTY_KEY: return "OBJECT_LITERAL_PROPERTY_KEY";
        case STATE::OBJECT_LITERAL_PROPERTY_COLON: return "OBJECT_LITERAL_PROPERTY_COLON";
        case STATE::OBJECT_LITERAL_PROPERTY_VALUE: return "OBJECT_LITERAL_PROPERTY_VALUE";
        case STATE::OBJECT_LITERAL_SEPARATOR: return "OBJECT_LITERAL_SEPARATOR";
        case STATE::IF_CONDITION_START: return "IF_CONDITION_START";
        case STATE::IF_CONSEQUENT: return "IF_CONSEQUENT";
        case STATE::IF_ALTERNATE_START: return "IF_ALTERNATE_START";
        case STATE::IF_ALTERNATE: return "IF_ALTERNATE";
        case STATE::BLOCK_STATEMENT_START: return "BLOCK_STATEMENT_START";
        case STATE::BLOCK_STATEMENT_BODY: return "BLOCK_STATEMENT_BODY";
        case STATE::NONE_W: return "W";
        case STATE::NONE_WH: return "WH";
        case STATE::NONE_WHI: return "WHI";
        case STATE::NONE_WHIL: return "WHIL";
        case STATE::NONE_WHILE: return "WHILE";
        case STATE::WHILE_CONDITION_START: return "WHILE_CONDITION_START";
        case STATE::WHILE_BODY: return "WHILE_BODY";
    }
    return "UNKNOWN_STATE";
}
